# Generated by Django 5.0.6 on 2024-08-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=255)),
                ('problem_number', models.IntegerField()),
                ('solution', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('time_complexity', models.CharField(max_length=100)),
                ('space_complexity', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
