# Generated by Django 5.0.6 on 2024-08-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0002_leetcodeproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1),
        ),
    ]
