# Generated by Django 5.0.6 on 2024-08-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0003_alter_leetcodeproblem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='leetcodeproblem',
            name='problem_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leetcodeproblem',
            name='status',
            field=models.BooleanField(default=False, help_text='Check if the problem is solved'),
        ),
    ]
