# Generated by Django 5.0.6 on 2024-08-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0004_leetcodeproblem_problem_link_leetcodeproblem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='problem_link',
            field=models.URLField(default='https://default.url'),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='space_complexity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='time_complexity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
