# Generated by Django 5.0.6 on 2024-08-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0005_alter_leetcodeproblem_problem_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6),
        ),
        migrations.AlterField(
            model_name='leetcodeproblem',
            name='problem_link',
            field=models.URLField(),
        ),
    ]
