# Generated by Django 5.0.6 on 2024-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0006_alter_leetcodeproblem_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='leetcodeproblem',
            name='topic',
        ),
        migrations.AddField(
            model_name='leetcodeproblem',
            name='topics',
            field=models.ManyToManyField(blank=True, to='leettracker.topic'),
        ),
    ]
