# Generated by Django 5.0.6 on 2024-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leettracker', '0007_topic_remove_leetcodeproblem_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
